USER = 'postgres'
PASSWORD = 'password'
DATABASE = 'postgres'
CREATE_MAIN = '''
CREATE TABLE IF NOT EXISTS ZNO (
    YEAR INTEGER,
    OUTID VARCHAR(255),
    Birth INTEGER,
    SEXTYPENAME VARCHAR(255),
    REGNAME VARCHAR(255),
    AREANAME VARCHAR(255),
    TERNAME VARCHAR(255),
    REGTYPENAME VARCHAR(255),
    TerTypeName VARCHAR(255),
    ClassProfileNAME VARCHAR(255),
    ClassLangName VARCHAR(255),
    EONAME VARCHAR(255),
    EOTYPENAME VARCHAR(255),
    EORegName VARCHAR(255),
    EOAreaName VARCHAR(255),
    EOTerName VARCHAR(255),
    EOParent VARCHAR(255),
    UkrTest VARCHAR(255),
    UkrTestStatus VARCHAR(255),
    UkrBall100 REAL,
    UkrBall12 REAL,
    UkrBall REAL,
    UkrAdaptScale REAL,
    UkrPTName VARCHAR(255),
    UkrPTRegName VARCHAR(255),
    UkrPTAreaName VARCHAR(255),
    UkrPTTerName VARCHAR(255),
    histTest VARCHAR(255),
    HistLang VARCHAR(255),
    histTestStatus VARCHAR(255),
    histBall100 REAL,
    histBall12 REAL,
    histBall REAL,
    histPTName VARCHAR(255),
    histPTRegName VARCHAR(255),
    histPTAreaName VARCHAR(255),
    histPTTerName VARCHAR(255),
    mathTest VARCHAR(255),
    mathLang VARCHAR(255),
    mathTestStatus VARCHAR(255),
    mathBall100 REAL,
    mathBall12 REAL,
    mathBall REAL,
    mathPTName VARCHAR(255),
    mathPTRegName VARCHAR(255),
    mathPTAreaName VARCHAR(255),
    mathPTTerName VARCHAR(255),
    physTest VARCHAR(255),
    physLang VARCHAR(255),
    physTestStatus VARCHAR(255),
    physBall100 REAL,
    physBall12 REAL,
    physBall REAL,
    physPTName VARCHAR(255),
    physPTRegName VARCHAR(255),
    physPTAreaName VARCHAR(255),
    physPTTerName VARCHAR(255),
    chemTest VARCHAR(255),
    chemLang VARCHAR(255),
    chemTestStatus VARCHAR(255),
    chemBall100 REAL,
    chemBall12 REAL,
    chemBall REAL,
    chemPTName VARCHAR(255),
    chemPTRegName VARCHAR(255),
    chemPTAreaName VARCHAR(255),
    chemPTTerName VARCHAR(255),
    bioTest VARCHAR(255),
    bioLang VARCHAR(255),
    bioTestStatus VARCHAR(255),
    bioBall100 REAL,
    bioBall12 REAL,
    bioBall REAL,
    bioPTName VARCHAR(255),
    bioPTRegName VARCHAR(255),
    bioPTAreaName VARCHAR(255),
    bioPTTerName VARCHAR(255),
    geoTest VARCHAR(255),
    geoLang VARCHAR(255),
    geoTestStatus VARCHAR(255),
    geoBall100 REAL,
    geoBall12 REAL,
    geoBall REAL,
    geoPTName VARCHAR(255),
    geoPTRegName VARCHAR(255),
    geoPTAreaName VARCHAR(255),
    geoPTTerName VARCHAR(255),
    engTest VARCHAR(255),
    engTestStatus VARCHAR(255),
    engBall100 REAL,
    engBall12 REAL,
    engDPALevel VARCHAR(255),
    engBall REAL,
    engPTName VARCHAR(255),
    engPTRegName VARCHAR(255),
    engPTAreaName VARCHAR(255),
    engPTTerName VARCHAR(255),
    fraTest VARCHAR(255),
    fraTestStatus VARCHAR(255),
    fraBall100 REAL,
    fraBall12 REAL,
    fraDPALevel VARCHAR(255),
    fraBall REAL,
    fraPTName VARCHAR(255),
    fraPTRegName VARCHAR(255),
    fraPTAreaName VARCHAR(255),
    fraPTTerName VARCHAR(255),
    deuTest VARCHAR(255),
    deuTestStatus VARCHAR(255),
    deuBall100 REAL,
    deuBall12 REAL,
    deuDPALevel VARCHAR(255),
    deuBall REAL,
    deuPTName VARCHAR(255),
    deuPTRegName VARCHAR(255),
    deuPTAreaName VARCHAR(255),
    deuPTTerName VARCHAR(255),
    spaTest VARCHAR(255),
    spaTestStatus VARCHAR(255),
    spaBall100 REAL,
    spaBall12 REAL,
    spaDPALevel VARCHAR(255),
    spaBall REAL,
    spaPTName VARCHAR(255),
    spaPTRegName VARCHAR(255),
    spaPTAreaName VARCHAR(255),
    spaPTTerName VARCHAR(255)
)
'''

CREATE_TMP = '''
CREATE TABLE IF NOT EXISTS TMP (
    YEAR INTEGER PRIMARY KEY,
    COUNTER INTEGER,
    DONE BOOLEAN
)
'''

INTEGER_FIELDS = ['YEAR', 'Birth']
REAL_FIELDS = [
    'UkrBall100', 'UkrBall12', 'UkrBall', 'UkrAdaptScale',
    'histBall100', 'histBall12', 'histBall',
    'mathBall100', 'mathBall12', 'mathBall',
    'physBall100', 'physBall12', 'physBall',
    'chemBall100', 'chemBall12', 'chemBall',
    'bioBall100', 'bioBall12', 'bioBall',
    'geoBall100', 'geoBall12', 'geoBall',
    'engBall100', 'engBall12', 'engBall',
    'fraBall100', 'fraBall12', 'fraBall',
    'deuBall100', 'deuBall12', 'deuBall',
    'spaBall100', 'spaBall12', 'spaBall'
]